In [1]:
import os

import cv2
import numpy as np
from PIL import Image

In [2]:
path_data = 'C:/Users/iscie/Desktop/computer-vision/Data/Recognition'
path_model = 'C:/Users/iscie/Desktop/computer-vision/Models/lbph_classifier_own.yml'

In [3]:
print(len(os.listdir(path_data)))

96


In [4]:
def get_image_data():
    paths = [os.path.join(path_data, f) for f in os.listdir(path_data)]

    faces = []
    ids = []

    for path in paths:
        image = Image.open(path).convert('L')
        image_np = np.array(image, 'uint8')

        id = int(path.split('.')[1])

        ids.append(id)
        faces.append(image_np)

    return np.array(ids), faces

In [5]:
ids, faces = get_image_data()

In [6]:
len(ids)

96

In [7]:
faces

[array([[ 54,  57,  60, ...,  57,  56,  56],
        [ 55,  58,  62, ...,  58,  58,  58],
        [ 56,  59,  63, ...,  58,  60,  62],
        ...,
        [ 69,  67,  73, ..., 245, 247, 247],
        [ 73,  69,  74, ..., 244, 247, 248],
        [ 76,  73,  77, ..., 245, 247, 248]], dtype=uint8),
 array([[ 60,  62,  63, ..., 107, 108, 108],
        [ 62,  63,  65, ..., 107, 108, 108],
        [ 63,  64,  66, ..., 109, 108, 108],
        ...,
        [109, 107, 107, ..., 189, 218, 237],
        [109, 107, 108, ..., 194, 217, 236],
        [110, 108, 108, ..., 199, 216, 235]], dtype=uint8),
 array([[ 50,  50,  50, ...,  55,  58,  59],
        [ 49,  49,  49, ...,  58,  59,  60],
        [ 50,  50,  50, ...,  64,  61,  59],
        ...,
        [ 70,  65,  62, ..., 155, 156, 157],
        [ 69,  63,  61, ..., 156, 160, 162],
        [ 76,  70,  69, ..., 156, 160, 162]], dtype=uint8),
 array([[ 56,  56,  56, ...,  76,  69,  63],
        [ 56,  56,  57, ...,  83,  77,  71],
        [ 57,  5

In [8]:
faces[0], faces[0].shape

(array([[ 54,  57,  60, ...,  57,  56,  56],
        [ 55,  58,  62, ...,  58,  58,  58],
        [ 56,  59,  63, ...,  58,  60,  62],
        ...,
        [ 69,  67,  73, ..., 245, 247, 247],
        [ 73,  69,  74, ..., 244, 247, 248],
        [ 76,  73,  77, ..., 245, 247, 248]], dtype=uint8),
 (464, 309))

In [ ]:
lbph_classifier = cv2.face.LBPHFaceRecognizer_create()
lbph_classifier.train(faces, ids)
lbph_classifier.write('lbph_classifier_own.yml')

# Drag the `lbph_classifier_own.yml` file into the `Models/` directory.

In [11]:
lbph_face_classifier = cv2.face.LBPHFaceRecognizer_create()
lbph_face_classifier.read(path_model)